{{- if and .Values.rbac.create .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-binding" (include "daemonsetlink-operator.leaderElectionRoleName" .) }}
  namespace: {{ include "daemonsetlink-operator.namespace" . }}
  labels:
    {{- include "daemonsetlink-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "daemonsetlink-operator.leaderElectionRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "daemonsetlink-operator.serviceAccountName" . }}
  namespace: {{ include "daemonsetlink-operator.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-binding" (include "daemonsetlink-operator.managerRoleName" .) }}
  labels:
    {{- include "daemonsetlink-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "daemonsetlink-operator.managerRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "daemonsetlink-operator.serviceAccountName" . }}
  namespace: {{ include "daemonsetlink-operator.namespace" . }}
{{- end -}}