{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "daemonsetlink-operator.leaderElectionRoleName" . }}
  namespace: {{ include "daemonsetlink-operator.namespace" . }}
  labels:
    {{- include "daemonsetlink-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "daemonsetlink-operator.daemonsetlinkEditorRoleName" . }}
  labels:
    {{- include "daemonsetlink-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - operators.artnetlab.tech
  resources:
  - daemonsetlinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.artnetlab.tech
  resources:
  - daemonsetlinks/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "daemonsetlink-operator.daemonsetlinkViewerRoleName" . }}
  labels:
    {{- include "daemonsetlink-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - operators.artnetlab.tech
  resources:
  - daemonsetlinks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.artnetlab.tech
  resources:
  - daemonsetlinks/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "daemonsetlink-operator.managerRoleName" . }}
  labels:
    {{- include "daemonsetlink-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.artnetlab.tech
  resources:
  - daemonsetlinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.artnetlab.tech
  resources:
  - daemonsetlinks/finalizers
  verbs:
  - update
- apiGroups:
  - operators.artnetlab.tech
  resources:
  - daemonsetlinks/status
  verbs:
  - get
  - patch
  - update
{{- end -}}