# permissions for end users to view daemonsetlinks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: daemonsetlink-operator
    app.kubernetes.io/managed-by: kustomize
  name: daemonsetlink-viewer-role
rules:
- apiGroups:
  - operators.operators.artnetlab.tech
  resources:
  - daemonsetlinks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.operators.artnetlab.tech
  resources:
  - daemonsetlinks/status
  verbs:
  - get
