---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.operators.artnetlab.tech
  resources:
  - daemonsetlinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.operators.artnetlab.tech
  resources:
  - daemonsetlinks/finalizers
  verbs:
  - update
- apiGroups:
  - operators.operators.artnetlab.tech
  resources:
  - daemonsetlinks/status
  verbs:
  - get
  - patch
  - update
