name: Release Helm Chart

on:
  push:
    tags:
      - "v0.1.*" # Minor release versions
  workflow_dispatch: # Allows manual triggering from the Actions tab
    inputs:
      tag_to_release:
        description: 'The git tag to create a chart release for (e.g., v0.1.0)'
        required: true
        # Example: default: 'v0.1.0' (optional default)

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To create GitHub releases and push to gh-pages
    steps:
      - name: Checkout code at specific tag
        uses: actions/checkout@v4
        with:
          # If triggered by a tag push, github.ref is 'refs/tags/vX.Y.Z'.
          # If triggered by workflow_dispatch, use the input tag.
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag_to_release || github.ref }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4 
        with:
          version: 'latest'

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: "."
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
